name: Run Python App

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: run action
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client
        pip install google-auth-httplib2 
        pip install google-auth-oauthlib
        pip install tabula-py
        pip install PyPDF2
        
        python process_pdf.py
